* teditor
*teditor* is a terminal based editor, written from scratch in C++. More details
about this editor can be found [[https://teju85.github.io/blog/tags.html#teditor][here]].
* Supported OS's
This has been only tested on cygwin till now. Should work for unix-based
systems. If it doesn't build/work properly on them, fixes are most welcome.
* Pre-reqs
Very minimal set of pre-reqs are needed for this project.
** Compile time
1. GNU-make (>= 4.2.1)
2. G++ (>= 5.4.0)
3. autoconf and automake - for building pcre2
4. doxygen (>= 1.8.13) - for documentation generation
** Runtime
1. curl - for downloading from web
2. mintty - for running the editor
3. git - to run git commands from inside the editor
* Download and Build
Currently, only been tested on cygwin with xterm-256.
#+BEGIN_SRC bash
$ git clone --recursive https://github.com/teju85/teditor
$ cd teditor
$ make -j teditor
$ ./bin/teditor
#+END_SRC
NOTE: If you have customized your minttyrc for the user configured colors,
then your experience with the default colors may vary!!
* Developers
** Generating documentation
It is expected that one has installed doxygen for this purpose. Generated
documentation can then be found inside the folder 'html'.
#+BEGIN_SRC bash
$ make doc
#+END_SRC
** Unit testing
Unit-tests are run via catch2.
#+BEGIN_SRC bash
$ make -j tests
#+END_SRC
