#pragma once

#include <stdint.h>
#include <core/pos2d.h>

namespace teditor {
namespace parser {

/** Represents a token that is being generated by the Lexer */
struct Token {
  /**
   * token type. Custom parsers are free to define their own types for their
   * internal use. But from an interface perspective, it'll always be an integer
   * for faster lookup.
   */
  uint32_t type;
  /** start of this token in the input stream */
  Point start;
  /** end of this token in the input stream */
  Point end;

  bool isEof() const { return type == End; }

  /** special reserved token for denoting EOF */
  static const uint32_t End;
};  // struct Token

}  // namespace parser
}  // namespace teditor
