const std::vector<KeyCombo> KeyCombo::Combos = {
  {Key_Insert|Meta_None, "[2~"},
  {Key_Delete|Meta_None, "[3~"},
  {Key_Home|Meta_None, "OH"},
  {Key_End|Meta_None, "OF"},
  {Key_PageUp|Meta_None, "[5~"},
  {Key_PageDown|Meta_None, "[6~"},

  {Key_Delete|Meta_Ctrl, "[3;5~"},
  {Key_Home|Meta_Ctrl, "[1;5H"},
  {Key_End|Meta_Ctrl, "[1;5F"},
  {Key_PageUp|Meta_Ctrl, "[5;5~"},
  {Key_PageDown|Meta_Ctrl, "[6;5~"},
  {Key_PageUp|Meta_Ctrl|Meta_Shift, "[5;6~"},
  {Key_PageDown|Meta_Ctrl|Meta_Shift, "[6;6~"},

  {Key_ArrowUp|Meta_None, "OA"},
  {Key_ArrowDown|Meta_None, "OB"},
  {Key_ArrowRight|Meta_None, "OC"},
  {Key_ArrowLeft|Meta_None, "OD"},

  {Key_ArrowUp|Meta_Shift, "[1;2A"},
  {Key_ArrowDown|Meta_Shift, "[1;2B"},
  {Key_ArrowRight|Meta_Shift, "[1;2C"},
  {Key_ArrowLeft|Meta_Shift, "[1;2D"},

  {Key_ArrowUp|Meta_Alt, "[1;3A"},
  {Key_ArrowDown|Meta_Alt, "[1;3B"},
  {Key_ArrowRight|Meta_Alt, "[1;3C"},
  {Key_ArrowLeft|Meta_Alt, "[1;3D"},

  {Key_ArrowUp|Meta_Ctrl, "[1;5A"},
  {Key_ArrowDown|Meta_Ctrl, "[1;5B"},
  {Key_ArrowRight|Meta_Ctrl, "[1;5C"},
  {Key_ArrowLeft|Meta_Ctrl, "[1;5D"},

  {Key_ArrowUp|Meta_Ctrl|Meta_Alt, "[1;7A"},
  {Key_ArrowDown|Meta_Ctrl|Meta_Alt, "[1;7B"},
  {Key_ArrowRight|Meta_Ctrl|Meta_Alt, "[1;7C"},
  {Key_ArrowLeft|Meta_Ctrl|Meta_Alt, "[1;7D"},

  {Key_ArrowUp|Meta_Ctrl|Meta_Shift, "[1;6A"},
  {Key_ArrowDown|Meta_Ctrl|Meta_Shift, "[1;6B"},
  {Key_ArrowRight|Meta_Ctrl|Meta_Shift, "[1;6C"},
  {Key_ArrowLeft|Meta_Ctrl|Meta_Shift, "[1;6D"},

  {Key_ArrowUp|Meta_Ctrl|Meta_Alt|Meta_Shift, "[1;8A"},
  {Key_ArrowDown|Meta_Ctrl|Meta_Alt|Meta_Shift, "[1;8B"},
  {Key_ArrowRight|Meta_Ctrl|Meta_Alt|Meta_Shift, "[1;8C"},
  {Key_ArrowLeft|Meta_Ctrl|Meta_Alt|Meta_Shift, "[1;8D"},

  {Key_Tab|Meta_Ctrl, "[1;5I"},
  {Key_Tab|Meta_Shift, "[Z"},
  {Key_Tab|Meta_Ctrl|Meta_Shift, "[1;6I"},

  {Key_F1|Meta_None, "OP"},
  {Key_F2|Meta_None, "OQ"},
  {Key_F3|Meta_None, "OR"},
  {Key_F4|Meta_None, "OS"},
  {Key_F5|Meta_None, "[15~"},
  {Key_F6|Meta_None, "[17~"},
  {Key_F7|Meta_None, "[18~"},
  {Key_F8|Meta_None, "[19~"},
  {Key_F9|Meta_None, "[20~"},
  {Key_F10|Meta_None, "[21~"},
  {Key_F11|Meta_None, "[23~"},
  {Key_F12|Meta_None, "[24~"},

  {Key_F1|Meta_Ctrl, "[1;5P"},
  {Key_F2|Meta_Ctrl, "[1;5Q"},
  {Key_F3|Meta_Ctrl, "[1;5R"},
  {Key_F4|Meta_Ctrl, "[1;5S"},
  {Key_F5|Meta_Ctrl, "[15;5~"},
  {Key_F6|Meta_Ctrl, "[17;5~"},
  {Key_F7|Meta_Ctrl, "[18;5~"},
  {Key_F8|Meta_Ctrl, "[19;5~"},
  {Key_F9|Meta_Ctrl, "[20;5~"},
  {Key_F10|Meta_Ctrl, "[21;5~"},
  {Key_F11|Meta_Ctrl, "[23;5~"},
  {Key_F12|Meta_Ctrl, "[24;5~"},

  {Key_F1|Meta_Ctrl|Meta_Shift, "[1;6P"},
  {Key_F2|Meta_Ctrl|Meta_Shift, "[1;6Q"},
  {Key_F3|Meta_Ctrl|Meta_Shift, "[1;6R"},
  {Key_F4|Meta_Ctrl|Meta_Shift, "[1;6S"},
  {Key_F5|Meta_Ctrl|Meta_Shift, "[15;6~"},
  {Key_F6|Meta_Ctrl|Meta_Shift, "[17;6~"},
  {Key_F7|Meta_Ctrl|Meta_Shift, "[18;6~"},
  {Key_F8|Meta_Ctrl|Meta_Shift, "[19;6~"},
  {Key_F9|Meta_Ctrl|Meta_Shift, "[20;6~"},
  {Key_F10|Meta_Ctrl|Meta_Shift, "[21;6~"},
  {Key_F11|Meta_Ctrl|Meta_Shift, "[23;6~"},
  {Key_F12|Meta_Ctrl|Meta_Shift, "[24;6~"}
};
