name: docs-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  TERM: xterm-256color

defaults:
  run:
    shell: bash

jobs:
  docs:
    runs-on: ubuntu-latest
    env:
      TEDITOR_BUILD_DOCS: 1
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build-and-test
