name: gh-pages

on:
  push:
    branches: [ master ]

env:
  DEPLOY_TOKEN: ${{ secrets.GHPAGESPUSH }}

defaults:
  run:
    shell: bash

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/gh-pages
